// frontend/packs/application.js
import "init";
import "./application.css";
import "consts/game_states.js"
import "services/game_loop_manager"
import "components/the-game/fb-main";
import "actions/add-new-player";
import "actions/do-jump";
import "components/player/player"